# Generated by Django 5.1.5 on 2025-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
